CREATE TABLE Users (
    UserId INT PRIMARY KEY IDENTITY,
    Email NVARCHAR(255) UNIQUE NOT NULL,
    PasswordHash NVARCHAR(255) NOT NULL
);

CREATE TABLE SearchHistory (
    SearchId INT PRIMARY KEY IDENTITY,
    UserId INT FOREIGN KEY REFERENCES Users(UserId),
    TickerSymbol NVARCHAR(10) NOT NULL,
    SearchDate DATETIME DEFAULT GETDATE()
);
